// import { Bebas_Neue, Poppins } from "next/font/google";
import "./globals.css";

// const bebas = Bebas_Neue({ subsets: ["latin"] });
// const poppins = Poppins({ subsets: ["latin"] });

export const metadata = {
  title: "FLoro do Themos Vagas",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className={''}>
        {children}
      </body>
    </html>
  );
}
